### PR TITLE
Adjust for `nnkCallKinds` == `CallNodes`

### LINKED ISSUE #293: CallNodes = nnkCallKinds
https://github.com/nim-works/cps/blob/5645eb5838e6d30d484fbe23d8c590201e520630/cps/transform.nim#L9-L10

https://github.com/nim-lang/Nim/pull/21833
https://github.com/nim-lang/Nim/pull/21829

### PR DESCRIPTION
**Pull request by Gruruya**
`nnkHiddenCallConv` was added to `nnkCallKinds`, so we need to shift some code. fixes #293

### CODE REVIEW

**Comment by Gruruya** [comment]
May have been a red herring, or at least it's not the thing failing tests. Seems that https://github.com/nim-lang/Nim/commit/c2bcfd8cd908265c358c60c4da137783b10a8549 is the real offender.

**Comment by disruptek** [comment]
Should we just add a new symbol for `CallNodes - {nnkHiddenCallConv}` so we don't have to make these changes everywhere next time?

**Comment by Gruruya** [comment]
Nice job

**Comment by disruptek** [comment]
> I kept nnkCallNodes in normalizedast, but I'm not sure if that's right or if there's any other instances that should be kept as nnkCallNodes as well

Well, where?

**Comment by Gruruya** [comment]
`abbreviation` particularly

**Comment by disruptek** [comment]
No big deal; the tests pass and we can add more when it fails.  :shrug:

**Comment by disruptek** [comment]
Nice to have this working again, thanks!

**Pull request merged**
